### ISSUE TITLE
[BUG]: The action fails when there's nothing to update

### ISSUE THREAD

**Issue by randomBrainstormer** [2hire/effective-octo-garbanzo#1]
## Bug Description
When there's nothing to update the action shows as failed.

![Schermata 2022-03-28 alle 13 09 01](https://user-images.githubusercontent.com/4858703/160385733-dd4196b7-b81a-4803-a561-09f145ad2a40.png)

## Expected Behavior
If there's nothing to update, return success.

## Actual Behavior
Action fails

## Possible Fix
maybe adding a "if empty or  undefined don't compare objects" logic

**Comment by Khalester** [comment]
Should be fixed with latest commits
